### ISSUE TITLE
when the level is completed show result and wait for user to press a key to return to main screen

### ISSUE THREAD

**Issue by SirNytram** [CubixL/PythonFunkin#12]
when the level is completed show result and wait for user to press a key to return to main screen

**Comment by CubixL** [comment]
To stay true to the original, I don't think I'll be implementing a results screen, but I did make the song end and save the score to the save file.
However, the system to detect if the level has ended is kind of mediocre; it thinks the level ends if:
1.  The mixer is idle (no sound is playing)
2.  The first target note is in the 'played' state

We might need to rework that, but I'm still closing the issue.
