### ISSUE TITLE
Game should display a list of available files

### ISSUE THREAD

**Issue by SirNytram** [CubixL/PythonFunkin#6]

**Comment by SirNytram** [comment]
you should use the os.listdir() function for all files ending with ".json"

for file in os.listdir('song')
   if file[:5] ='.json':
      #add file to list of possible songs

**Comment by SirNytram** [comment]
self.Buttons.append( { 
            'section' : 'level',
            'imgNormal' : GameText(self, GameFont(self), 'play', (17, 17)),
            'imgSelected' : GameText(self, GameFont(self), 'play', (17, 17), rgb=(255,1,1)),
        })

**Comment by CubixL** [comment]
added
